<?php
/**
 * Created by PhpStorm.
 * User: yangyu
 * Date: 2017/1/8
 * Time: 19:46
 */
namespace app\models;
use yii\db\ActiveRecord;
class Test extends ActiveRecord{
   /* public static function tableName()
   {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
*/
   public function rules()
   {
       return[
           ["id","integer"],
           ["tittle","string","length"=>[0,7]]
       ];
   }
}